name: Cut Release

on:
  repository_dispatch:
    types: [release-next]

env:
  CI: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_REPO_ACCESS }}

      - name: clone
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_REPO_ACCESS }}

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # This only serves to use the cache from snapshot/test runs.
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: configure env
        env:
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set loglevel error
          npm config set progress false
          npm config set '@nti:registry' "$NPM_REGISTRY"
          npm config set "${NPM_REGISTRY/https:/}/:_authToken" "$NPM_TOKEN"
          git config user.email support@nextthought.com
          git config user.name nti-jarvis

      - name: Generate release build
        run: npx -y @nti/release

      - name: notify of failure
        if: failure()
        env:
          LINK: ${{ format('<https://github.com/{0}/actions|{0}@{1} failed to cut release>', github.repository, github.ref) }}
        run: |
          MESSAGE="{\"text\": \":stop_sign: $LINK\" }"
          curl -i -X POST -H 'Content-Type: application/json' -d "$MESSAGE" ${{secrets.MM_HOOK}}
